### ISSUE TITLE
Fix athena ts 3 deployment

### ISSUE THREAD

**Issue by undernagruzez** [pal03377/Athena-New#294]
### Please describe the bug

The user whose credentials were used to deploy to athena ts3 is now inactive. Should be fixed. Also, it would be preferable to consider a solution to not store the credentials in deployment scripts, but to use environment variables for this purpose.

### To Reproduce

1. Open a PR and put the deployment label.
2. Wait a bit.
3. Observe a deployment error.

### Expected behavior

The PR should be deployed to the athena ts3 without any issues.

### What module is this bug related to?

Other (specify in "Additional context")

**Comment by marlon-luca-bu** [comment]
Hi @maximiliansoelch I assigned you to this task, since you said in the meeting you will have a look :-). So we can track the progress and discussions

**Comment by maximiliansoelch** [comment]
The issue is resolved for now. The problem is that the ssh key used for the GitHub deployment always gets overwritten when someone requests ssh access to the server by the admins. We need to talk to them to make the key persistent.
