### ISSUE TITLE
Use different schemas for graded and non-graded feedback.

### ISSUE THREAD

**Issue by undernagruzez** [pal03377/Athena-New#318]
### Is your feature request related to a problem?

Right now, Athena reuses the schema for graded feedback suggestions to generate non-graded feedback suggestions. The schema contains fields like credits or grading instructions. Do we still need these fields?

### Describe the solution you'd like

Decide whether to keep the existing schema or develop a new one.

**Comment by FelixTJDietrich** [comment]
This goes along with using different decorators for non-graded and graded feedback.

**Comment by undernagruzez** [comment]
Modified https://github.com/ls1intum/Athena/issues/319.
