### ISSUE TITLE
Use different decorators and schemas for graded and non-graded feedback suggestions.

### ISSUE THREAD

**Issue by undernagruzez** [pal03377/Athena-New#319]
### Is your feature request related to a problem?

We currently use a decorator suggest_feedback for both graded and non-graded feedback suggestions. It might make sense to use different decorators.

Also, Athena reuses the schema for graded feedback suggestions to generate non-graded feedback suggestions. The schema contains fields like credits or grading instructions. Do we still need these fields?

### Describe the solution you'd like

Separate the logic behind the decorators. Also, the modules are scanned automatically to detect the features they support.
Decide whether to keep the existing schema or develop a new one.

**Comment by FelixTJDietrich** [comment]
I think this can be done in combination with #318.

**Comment by FelixTJDietrich** [comment]
This might be obsolete for now, we have to discuss with @maximiliansoelch

**Comment by FelixTJDietrich** [comment]
We will no longer do this
