### ISSUE TITLE
Playground: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended

### ISSUE THREAD

**Issue by pal03377** [pal03377/Athena-New#60]
Steps to reproduce:
- Open the playground
- Check the `Use custom module config` checkbox
- Look for the message in DevTools:
![screenshot-2023-07-24_001680](https://github.com/ls1intum/Athena/assets/9006596/2f622ac8-319e-4285-a833-9cb6bcfad23e)

I think we should somehow fix this, but I believe it's a bit difficult because of how the custom module config works (? @FelixTJDietrich )

**Comment by pal03377** [comment]
introduced in #52

**Comment by FelixTJDietrich** [comment]
Seems to be related to https://github.com/rjsf-team/react-jsonschema-form/issues/1794

**Comment by FelixTJDietrich** [comment]
The related issue is closed now and I don't see the error message in the playground anymore
